package filmfestival;
// Generated Jan 20, 2018 12:55:52 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private int idfestival;
     private String naziv;
     private Date datumPocetka;
     private Date datumKraja;
     private String informacije;
     private String mesta;
     private Set<Projekcija> projekcijas = new HashSet<Projekcija>(0);

    public Festival() {
    }

	
    public Festival(int idfestival) {
        this.idfestival = idfestival;
    }
    public Festival(int idfestival, String naziv, Date datumPocetka, Date datumKraja, String informacije, String mesta, Set<Projekcija> projekcijas) {
       this.idfestival = idfestival;
       this.naziv = naziv;
       this.datumPocetka = datumPocetka;
       this.datumKraja = datumKraja;
       this.informacije = informacije;
       this.mesta = mesta;
       this.projekcijas = projekcijas;
    }
   
    public int getIdfestival() {
        return this.idfestival;
    }
    
    public void setIdfestival(int idfestival) {
        this.idfestival = idfestival;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getDatumPocetka() {
        return this.datumPocetka;
    }
    
    public void setDatumPocetka(Date datumPocetka) {
        this.datumPocetka = datumPocetka;
    }
    public Date getDatumKraja() {
        return this.datumKraja;
    }
    
    public void setDatumKraja(Date datumKraja) {
        this.datumKraja = datumKraja;
    }
    public String getInformacije() {
        return this.informacije;
    }
    
    public void setInformacije(String informacije) {
        this.informacije = informacije;
    }
    public String getMesta() {
        return this.mesta;
    }
    
    public void setMesta(String mesta) {
        this.mesta = mesta;
    }
    public Set<Projekcija> getProjekcijas() {
        return this.projekcijas;
    }
    
    public void setProjekcijas(Set<Projekcija> projekcijas) {
        this.projekcijas = projekcijas;
    }




}


