package filmfestival;
// Generated Jan 20, 2018 12:55:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private int idfilm;
     private String naziv;
     private String originalniNaziv;
     private String godinaIzdanja;
     private String kratakOpis;
     private int idfestival;
     private String reziser;
     private String glumci;
     private String trajanje;
     private String zemlja;
     private String imdbLink;
     private String rottenTomatoLink;
     private String youTubeLink;
     private Set<Projekcija> projekcijas = new HashSet<Projekcija>(0);
     private Set<Komentar> komentars = new HashSet<Komentar>(0);

    public Film() {
    }

	
    public Film(int idfilm, int idfestival) {
        this.idfilm = idfilm;
        this.idfestival = idfestival;
    }
    public Film(int idfilm, String naziv, String originalniNaziv, String godinaIzdanja, String kratakOpis, int idfestival, String reziser, String glumci, String trajanje, String zemlja, String imdbLink, String rottenTomatoLink, String youTubeLink, Set<Projekcija> projekcijas, Set<Komentar> komentars) {
       this.idfilm = idfilm;
       this.naziv = naziv;
       this.originalniNaziv = originalniNaziv;
       this.godinaIzdanja = godinaIzdanja;
       this.kratakOpis = kratakOpis;
       this.idfestival = idfestival;
       this.reziser = reziser;
       this.glumci = glumci;
       this.trajanje = trajanje;
       this.zemlja = zemlja;
       this.imdbLink = imdbLink;
       this.rottenTomatoLink = rottenTomatoLink;
       this.youTubeLink = youTubeLink;
       this.projekcijas = projekcijas;
       this.komentars = komentars;
    }
   
    public int getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(int idfilm) {
        this.idfilm = idfilm;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getOriginalniNaziv() {
        return this.originalniNaziv;
    }
    
    public void setOriginalniNaziv(String originalniNaziv) {
        this.originalniNaziv = originalniNaziv;
    }
    public String getGodinaIzdanja() {
        return this.godinaIzdanja;
    }
    
    public void setGodinaIzdanja(String godinaIzdanja) {
        this.godinaIzdanja = godinaIzdanja;
    }
    public String getKratakOpis() {
        return this.kratakOpis;
    }
    
    public void setKratakOpis(String kratakOpis) {
        this.kratakOpis = kratakOpis;
    }
    public int getIdfestival() {
        return this.idfestival;
    }
    
    public void setIdfestival(int idfestival) {
        this.idfestival = idfestival;
    }
    public String getReziser() {
        return this.reziser;
    }
    
    public void setReziser(String reziser) {
        this.reziser = reziser;
    }
    public String getGlumci() {
        return this.glumci;
    }
    
    public void setGlumci(String glumci) {
        this.glumci = glumci;
    }
    public String getTrajanje() {
        return this.trajanje;
    }
    
    public void setTrajanje(String trajanje) {
        this.trajanje = trajanje;
    }
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }
    public String getImdbLink() {
        return this.imdbLink;
    }
    
    public void setImdbLink(String imdbLink) {
        this.imdbLink = imdbLink;
    }
    public String getRottenTomatoLink() {
        return this.rottenTomatoLink;
    }
    
    public void setRottenTomatoLink(String rottenTomatoLink) {
        this.rottenTomatoLink = rottenTomatoLink;
    }
    public String getYouTubeLink() {
        return this.youTubeLink;
    }
    
    public void setYouTubeLink(String youTubeLink) {
        this.youTubeLink = youTubeLink;
    }
    public Set<Projekcija> getProjekcijas() {
        return this.projekcijas;
    }
    
    public void setProjekcijas(Set<Projekcija> projekcijas) {
        this.projekcijas = projekcijas;
    }
    public Set<Komentar> getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set<Komentar> komentars) {
        this.komentars = komentars;
    }




}


