package filmfestival;
// Generated Jan 20, 2018 12:55:52 AM by Hibernate Tools 4.3.1



/**
 * Komentar generated by hbm2java
 */
public class Komentar  implements java.io.Serializable {


     private int idkomentar;
     private Film film;
     private Korisnik korisnik;
     private String sadrzaj;
     private int ocena;

    public Komentar() {
    }

    public Komentar(int idkomentar, Film film, Korisnik korisnik, String sadrzaj, int ocena) {
       this.idkomentar = idkomentar;
       this.film = film;
       this.korisnik = korisnik;
       this.sadrzaj = sadrzaj;
       this.ocena = ocena;
    }
   
    public int getIdkomentar() {
        return this.idkomentar;
    }
    
    public void setIdkomentar(int idkomentar) {
        this.idkomentar = idkomentar;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getSadrzaj() {
        return this.sadrzaj;
    }
    
    public void setSadrzaj(String sadrzaj) {
        this.sadrzaj = sadrzaj;
    }
    public int getOcena() {
        return this.ocena;
    }
    
    public void setOcena(int ocena) {
        this.ocena = ocena;
    }




}


