package filmfestival;
// Generated Jan 20, 2018 12:55:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String korisnickoIme;
     private String ime;
     private String prezime;
     private String lozinka;
     private String kontaktTelefon;
     private String email;
     private String tip;
     private Integer maksBrojUlaznica;
     private Set<Rezervacija> rezervacijas = new HashSet<Rezervacija>(0);
     private Set<Komentar> komentars = new HashSet<Komentar>(0);

    public Korisnik() {
    }

	
    public Korisnik(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public Korisnik(String korisnickoIme, String ime, String prezime, String lozinka, String kontaktTelefon, String email, String tip, Integer maksBrojUlaznica, Set<Rezervacija> rezervacijas, Set<Komentar> komentars) {
       this.korisnickoIme = korisnickoIme;
       this.ime = ime;
       this.prezime = prezime;
       this.lozinka = lozinka;
       this.kontaktTelefon = kontaktTelefon;
       this.email = email;
       this.tip = tip;
       this.maksBrojUlaznica = maksBrojUlaznica;
       this.rezervacijas = rezervacijas;
       this.komentars = komentars;
    }
   
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getKontaktTelefon() {
        return this.kontaktTelefon;
    }
    
    public void setKontaktTelefon(String kontaktTelefon) {
        this.kontaktTelefon = kontaktTelefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public Integer getMaksBrojUlaznica() {
        return this.maksBrojUlaznica;
    }
    
    public void setMaksBrojUlaznica(Integer maksBrojUlaznica) {
        this.maksBrojUlaznica = maksBrojUlaznica;
    }
    public Set<Rezervacija> getRezervacijas() {
        return this.rezervacijas;
    }
    
    public void setRezervacijas(Set<Rezervacija> rezervacijas) {
        this.rezervacijas = rezervacijas;
    }
    public Set<Komentar> getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set<Komentar> komentars) {
        this.komentars = komentars;
    }




}


