package filmfestival;
// Generated Jan 20, 2018 12:55:52 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rezervacija generated by hbm2java
 */
public class Rezervacija  implements java.io.Serializable {


     private int idrezervacija;
     private Korisnik korisnik;
     private Projekcija projekcija;
     private Integer brojUlaznica;
     private String kod;
     private Date vremeRezervacije;
     private String status;

    public Rezervacija() {
    }

	
    public Rezervacija(int idrezervacija, Korisnik korisnik, Projekcija projekcija, String kod) {
        this.idrezervacija = idrezervacija;
        this.korisnik = korisnik;
        this.projekcija = projekcija;
        this.kod = kod;
    }
    public Rezervacija(int idrezervacija, Korisnik korisnik, Projekcija projekcija, Integer brojUlaznica, String kod, Date vremeRezervacije, String status) {
       this.idrezervacija = idrezervacija;
       this.korisnik = korisnik;
       this.projekcija = projekcija;
       this.brojUlaznica = brojUlaznica;
       this.kod = kod;
       this.vremeRezervacije = vremeRezervacije;
       this.status = status;
    }
   
    public int getIdrezervacija() {
        return this.idrezervacija;
    }
    
    public void setIdrezervacija(int idrezervacija) {
        this.idrezervacija = idrezervacija;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Projekcija getProjekcija() {
        return this.projekcija;
    }
    
    public void setProjekcija(Projekcija projekcija) {
        this.projekcija = projekcija;
    }
    public Integer getBrojUlaznica() {
        return this.brojUlaznica;
    }
    
    public void setBrojUlaznica(Integer brojUlaznica) {
        this.brojUlaznica = brojUlaznica;
    }
    public String getKod() {
        return this.kod;
    }
    
    public void setKod(String kod) {
        this.kod = kod;
    }
    public Date getVremeRezervacije() {
        return this.vremeRezervacije;
    }
    
    public void setVremeRezervacije(Date vremeRezervacije) {
        this.vremeRezervacije = vremeRezervacije;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


